version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-name: "@medusajs/*"
    groups:
      medusa:
        dependency-type: "development"
        patterns:
          - "@medusajs/*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
